### ISSUE TITLE
getting  error on hashingcrypto.js:74 while trying to ng serve

### ISSUE THREAD

**Issue by fauzyahmad** [webmaxru/pwa-workshop-angular#5]
86% hashingcrypto.js:74
 this._handle.update(data, encoding);

TypeError: Data must be a string or a buffer
    at TypeError (native)
    at Hash.update (crypto.js:74:16)
    at HarmonyExportImportedSpecifierDependency.updateHash (E:\Project Web dan Native\ProjectAngular2\pwa-workshop-angular\node_modules\webpack\lib\dependencies\Harmony
ExportImportedSpecifierDependency.js:144:8)
    at E:\Project Web dan Native\ProjectAngular2\pwa-workshop-angular\node_modules\webpack\lib\DependenciesBlock.js:33:5
    at Array.forEach (native)
    at NormalModule.DependenciesBlock.updateHash (E:\Project Web dan Native\ProjectAngular2\pwa-workshop-angular\node_modules\webpack\lib\DependenciesBlock.js:32:20)
    at NormalModule.Module.updateHash (E:\Project Web dan Native\ProjectAngular2\pwa-workshop-angular\node_modules\webpack\lib\Module.js:162:41)
    at NormalModule.updateHash (E:\Project Web dan Native\ProjectAngular2\pwa-workshop-angular\node_modules\webpack\lib\NormalModule.js:327:30)
    at modules.forEach.m (E:\Project Web dan Native\ProjectAngular2\pwa-workshop-angular\node_modules\webpack\lib\Chunk.js:253:31)
    at Array.forEach (native)
    at Chunk.updateHash (E:\Project Web dan Native\ProjectAngular2\pwa-workshop-angular\node_modules\webpack\lib\Chunk.js:253:16)
    at Compilation.createHash (E:\Project Web dan Native\ProjectAngular2\pwa-workshop-angular\node_modules\webpack\lib\Compilation.js:1121:10)
    at sealPart2 (E:\Project Web dan Native\ProjectAngular2\pwa-workshop-angular\node_modules\webpack\lib\Compilation.js:605:9)
    at next (E:\Project Web dan Native\ProjectAngular2\pwa-workshop-angular\node_modules\tapable\lib\Tapable.js:202:11)
    at Compilation.<anonymous> (E:\Project Web dan Native\ProjectAngular2\pwa-workshop-angular\node_modules\webpack\lib\ProgressPlugin.js:110:5)
    at next (E:\Project Web dan Native\ProjectAngular2\pwa-workshop-angular\node_modules\tapable\lib\Tapable.js:204:14)

This error show in my cmd while trying to ng serve.

**Comment by cwhaught** [comment]
I am seeing the same issue.

**Comment by webmaxru** [comment]
Fixed with https://github.com/webmaxru/pwa-workshop-angular/commit/df1cb602f15c2178d6eeef46ec2bb6541f5a49b6
A temporary fix before upgrading to a new AM beta (this is why it's pushed only for `master`)
